name: '[_shared] deploy-lambda'

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo {{ input.target }} #1

  build2:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo {{ input.target }} #2
