name: '[_shared] deploy-lambda'

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo ${{ inputs.target }} - 1

  deploy_depencdences:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo ${{ inputs.target }} - 2
